### ISSUE TITLE
Inference Error

### ISSUE THREAD

**Issue by wubangcai** [QwenLM/Qwen2-VL#162]
1. I used  `llamafactory-cli train examples/train_lora/qwen2vl_lora_sft.yaml` to train a model
2. I used `llamafactory-cli export examples/merge_lora/qwen2vl_lora_sft.yaml` to get merged model
3. `generated_ids = model.generate(**inputs, max_new_tokens=128)` return following error：
  ```
File "infer_demo.py", line 70, in <module>
    generated_ids = model.generate(**inputs, max_new_tokens=128)
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/transformers/generation/utils.py", line 2020, in generate
    result = self._sample(
  File "/usr/local/lib/python3.8/dist-packages/transformers/generation/utils.py", line 2966, in _sample
    outputs = self(**model_inputs, return_dict=True)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/transformers/models/qwen2_vl/modeling_qwen2_vl.py", line 1589, in forward
    inputs_embeds[image_mask] = image_embeds
RuntimeError: shape mismatch: value tensor of shape [54, 3584] cannot be broadcast to indexing result of shape [0, 3584]
```

**Comment by wubangcai** [comment]
By the way, in the same inference demo, the official original model` Qwen2-VL-7B-Instruct` was able to run, but my fine-tuned using lora and merged model return this error.

**Comment by gujiacheng** [comment]
same error

**Comment by zhyxun** [comment]
Same error. Have you soved it?

**Comment by gujiacheng** [comment]
solved by increase 'cutoff_len' in yaml file

**Comment by wubangcai** [comment]
@gujiacheng @zhyxun  I didn't solve it with `cutoff_len`.  I found that the `chat_template.json` file was missing from my merged fine-tuning model folder. After I copied it from the original model folder : `Qwen2-VL-7B-Instruct`, I could use the official demo for normal inference.

**Comment by wubangcai** [comment]
Here  is my inference code, modified from the official demo.
```
from transformers import Qwen2VLForConditionalGeneration, AutoTokenizer, AutoProcessor
from qwen_vl_utils import process_vision_info
import torch

# default: Load the model on the available device(s)
model = Qwen2VLForConditionalGeneration.from_pretrained(
    "saves/qwen2_vl-7b/lora/sft_merge_model", torch_dtype=torch.bfloat16, device_map="auto"
)


# default processer
processor = AutoProcessor.from_pretrained("saves/qwen2_vl-7b/lora/sft_merge_model") 
# 这里未保存chat_template.json 需要从原始模型那里复制过来 

messages = [
    {
        "role": "user",
        "content": [
            {
                "type": "image",
                "image": "https://qianwen-res.oss-cn-beijing.aliyuncs.com/Qwen-VL/assets/demo.jpeg",
                "min_pixels": 50176, 
                "max_pixels": 50176,
            },
            {"type": "text", "text": "请用中文描述这张图片"},
        ],
    }
]


# Preparation for inference
text = processor.apply_chat_template(
    messages, tokenize=False, add_generation_prompt=True
)
image_inputs, video_inputs = process_vision_info(messages)  # 这里会将图像resize 到目标大小
inputs = processor(
    text=[text],
    images=image_inputs,
    videos=video_inputs,
    padding=True,
    return_tensors="pt",
)
inputs = inputs.to("cuda")

generated_ids = model.generate(**inputs, max_new_tokens=128)
generated_ids_trimmed = [
    out_ids[len(in_ids) :] for in_ids, out_ids in zip(inputs.input_ids, generated_ids)
]
output_text = processor.batch_decode(
    generated_ids_trimmed, skip_special_tokens=True, clean_up_tokenization_spaces=False
)
print(output_text)
```
